#!/bin/bash
echo "switch case starts"
case $1 in
     start)
       sudo systemctl start httpd.service
       echo "systemctl started httpd.service" 
       ;;
     stop)
       sudo systemctl stop httpd.service
       echo "systemctl stopped httpd.service" 
       ;;
     restart)
        sudo  systemctl restart httpd.service
        echo "systemctl restarted httpd.service " 
        ;;
      *)
      echo "you entered an invalid option"
      echo "please enter start, stop or restart option" 
      ;;
esac
echo "echo switch case ends"